MyFinance/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class UsuarioController : Controller
    {
        [HttpGet]
        public IActionResult Login(int? id)
        {
            if (id != null)
            {
                if (id == 0)
                {
                    HttpContext.Session.SetString("IdUsuarioLogado", string.Empty);
                    HttpContext.Session.SetString("NomeUsuarioLogado", string.Empty);
                }
            }

            return View();
        }

        [HttpPost]
        public IActionResult ValidarLogin(UsuarioModel usuario)
        {
            bool login = usuario.ValidarLogin();
            if (login)
            {
                HttpContext.Session.SetString("NomeUsuarioLogado", usuario.Nome);
                HttpContext.Session.SetString("IdUsuarioLogado", usuario.Id.ToString());
                return RedirectToAction("Menu", "Home");
            }
            else
            {
                TempData["MensagemLoginInvalido"] = "Dados de login inválidos!";
                return RedirectToAction("Login");
            }
        }

        [HttpPost]       
        public IActionResult Registrar(UsuarioModel usuario)
        {
            if (ModelState.IsValid)
            {
                //Registrar o usuário
                usuario.RegistrarUsuario();
                return RedirectToAction("Sucesso");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            return View();
        }

        public IActionResult Sucesso()
        {
            return View();
        }
    }
}

MyFinance/Views/Usuario/Login.cshtml
@model UsuarioModel


@{
    Layout = "../Shared/_LayoutLogin.cshtml";
}

<div class="container" style="background-color:rgba(239, 239, 239, 0.95); border-radius: 10px; padding:20px; width:300px;">


    <form asp-controller="Usuario" asp-action="ValidarLogin">
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" asp-for="Email">
        </div>
        <div class="form-group">
            <label for="pwd">Senha:</label>
            <input type="password" class="form-control" asp-for="Senha">
        </div>
        <div class="checkbox">
            <label><input type="checkbox"> Lembrar meu acesso</label>
        </div>

        <button type="button" class="btn btn-primary" onclick="javascript:window.location.href='../Usuario/Registrar'">Registrar</button>
        <button type="submit" class="btn btn-default">Entrar</button>
    </form>
</div>

MyFinance/Views/Usuario/Registrar.cshtml
@model UsuarioModel

@{
    Layout = "../Shared/_LayoutLogin.cshtml";
}


<div class="container" style="background-color:rgba(239, 239, 239, 0.95); border-radius: 10px; padding:20px; width:500px;">
    <h3>Registrar minha conta!</h3>
    <br />
    <form asp-controller="Usuario" asp-action="Registrar" novalidate>
        <div class="form-group">
            <label for="email">Nome:</label>
            <input type="text" class="form-control" asp-for="Nome">
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" asp-for="Email">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="pwd">Senha:</label>
            <input type="password" class="form-control" asp-for="Senha">
            <span asp-validation-for="Senha" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="pwd">Data de Nascimento:</label>
            <input type="date" class="form-control" asp-for="Data_Nascimento">
            <span asp-validation-for="Data_Nascimento" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-block btn-success">Registrar</button>
        <button type="button" class="btn btn-block btn-primary" onclick="javascript:window.location.href='../Usuario/Login'">Login</button>
    </form>
</div>

MyFinance/Views/Usuario/Sucesso.cshtml
@{
    Layout = "../Shared/_LayoutLogin.cshtml";
}

<div class="alert-success">
    <h2>Parabéns sua conta foi criada com sucesso! Clique <a href="../Usuario/Login">aqui</a> para efetuar login no sistema...</h2>
</div>