MyFinance/Controllers/PlanoContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class PlanoContaController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;

        public PlanoContaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            PlanoContaModel objPlanoContas = new PlanoContaModel(HttpContextAccessor);
            ViewBag.ListaPlanoContas = objPlanoContas.ListaPlanoContas();
            return View();
        }

        [HttpPost]
        public IActionResult CriarPlanoConta(PlanoContaModel formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.HttpContextAccessor = HttpContextAccessor;
                formulario.Insert();
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult CriarPlanoConta(int? id)
        {
            if (id !=null)
            {
                PlanoContaModel objPlanoContas = new PlanoContaModel(HttpContextAccessor);
                ViewBag.Registro = objPlanoContas.CarregarRegistro(id);
            }

            return View();
        }

        [HttpGet]
        public IActionResult ExcluirPlanoConta(int id)
        {
            PlanoContaModel objPlanoConta = new PlanoContaModel(HttpContextAccessor);
            objPlanoConta.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

MyFinance/Views/PlanoConta/CriarPlanoConta.cshtml
@model PlanoContaModel

<h3>Criar Plano de Contas</h3>

@{
    var vDescricao = "";
    var vTipo = "";
    var vId = 0;

    try
    {
        vId = int.Parse(@ViewBag.Registro.Id.ToString());
        vDescricao = @ViewBag.Registro.Descricao.ToString();
        vTipo = @ViewBag.Registro.Tipo.ToString();
    }
    catch { }    
}

<form asp-controller="PlanoConta" asp-action="CriarPlanoConta">
    <input type="hidden" asp-for="Id" value="@vId" />

    <div class="form-group">
        <label>Descrição:</label>
        <input type="text" class="form-control" asp-for="Descricao" value="@vDescricao">
        <span asp-validation-for="Descricao" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Tipo:</label>
   
            @{
                if (vTipo == "R")
                {
                    <div class="radio"><label><input type="radio" asp-for="Tipo" value="R" checked>Receita</label></div>
                    <div class="radio"><label><input type="radio" asp-for="Tipo" value="D" unchecked>Despesa</label></div>
                }
                else
                {
                    <div class="radio"><label><input type="radio" asp-for="Tipo" value="R" unchecked>Receita</label></div>
                    <div class="radio"><label><input type="radio" asp-for="Tipo" value="D" checked>Despesa</label></div>
                }
            }
    </div>

    <button type="submit" class="btn btn-block btn-success">Registrar</button>

</form>

MyFinance/Views/PlanoConta/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h3>Plano de Contas</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>#</th>
            <th>ID</th>
            <th>Descrição</th>
            <th>Tipo</th>
        </tr>
    </thead>

    @{
        foreach (var item in (List<PlanoContaModel>)ViewBag.ListaPlanoContas)
        {
            <tbody>
                <tr>
                    <td><button type="button" class="btn btn-primary" onclick="Editar(@item.Id.ToString())">Editar</button></td>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
                    <td>@item.Id.ToString()</td>
                    <td>@item.Descricao.ToString()</td>
                    <td>@item.Tipo.ToString().Replace("R", "Receita").Replace("D", "Despesa")</td>
                </tr>
            </tbody>
        }
    }

</table>

<button type="button" class="btn btn-block btn-primary" onclick="CriarPlanoConta()">Criar Plano de Conta</button>

<script>
    function CriarPlanoConta()
    {
        window.location.href = "../PlanoConta/CriarPlanoConta";
    }

    function Excluir(id_conta)
    {
        window.location.href = "../PlanoConta/ExcluirPlanoConta/" + id_conta;
    }

    function Editar(id_conta) {
        window.location.href = "../PlanoConta/CriarPlanoConta/" + id_conta;
    }
</script>