MyFinance/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;
using Microsoft.AspNetCore.Http;

namespace MyFinance.Controllers
{
    public class ContaController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;

        public ContaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            ContaModel objConta = new ContaModel(HttpContextAccessor);
            ViewBag.ListaConta = objConta.ListaConta();
            return View();
        }

        [HttpPost]
        public IActionResult CriarConta(ContaModel formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.HttpContextAccessor = HttpContextAccessor;
                formulario.Insert();
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult CriarConta()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ExcluirConta(int id)
        {
            ContaModel objConta = new ContaModel(HttpContextAccessor);
            objConta.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

MyFinance/Views/Conta/CriarConta.cshtml
@model ContaModel   

@{
    ViewData["Title"] = "CriarConta";
}

<h3>Criar Conta</h3>

<form asp-controller="Conta" asp-action="CriarConta">
    
    <div class="form-group">
        <label>Nome:</label>
        <input type="text" class="form-control" asp-for="Nome">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Saldo:</label>
        <input type="text" class="form-control" asp-for="Saldo">
        <span asp-validation-for="Saldo" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-block btn-success">Registrar</button>

</form>

MyFinance/Views/Conta/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h3>Minhas Contas</h3>

<table class="table table-bordered">    
    <thead>
        <tr>
            <th>#</th>
            <th>ID</th>
            <th>Nome</th>
            <th>Saldo</th>
        </tr>
    </thead>

    @{
        foreach (var item in (List<ContaModel>)ViewBag.ListaConta)
        {
            <tbody>
                <tr>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
                    <td>@item.Id.ToString()</td>
                    <td>@item.Nome.ToString()</td>
                    <td>R$ @item.Saldo.ToString()</td>
                </tr>
            </tbody>
        }        
    }

</table>

<button type="button" class="btn btn-block btn-primary" onclick="CriarConta()">Criar Conta</button>

<script>
    function CriarConta()
    {
        window.location.href = "../Conta/CriarConta";        
    }

    function Excluir(id_conta)
    {        
        window.location.href = "../Conta/ExcluirConta/" + id_conta; 
    }
</script>