MyFinance/Controllers/TransacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class TransacaoController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;

        public TransacaoController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            TransacaoModel objTransacao = new TransacaoModel(HttpContextAccessor);
            ViewBag.ListaTransacao = objTransacao.ListaTransacao();
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(TransacaoModel formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.HttpContextAccessor = HttpContextAccessor;
                formulario.Insert();
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Registrar(int? id)
        {
            if (id != null)
            {
                TransacaoModel objTransacao = new TransacaoModel(HttpContextAccessor);
                ViewBag.Registro = objTransacao.CarregarRegistro(id);
            }
            ViewBag.ListaContas = new ContaModel(HttpContextAccessor).ListaConta();
            ViewBag.ListaPlanoContas = new PlanoContaModel(HttpContextAccessor).ListaPlanoContas();

            return View();
        }

        [HttpGet]
        public IActionResult ExcluirTransacao(int id)
        {    
            TransacaoModel objTransacao = new TransacaoModel(HttpContextAccessor);
            ViewBag.Registro = objTransacao.CarregarRegistro(id);         
            return View();
        }


        [HttpGet]
        public IActionResult Excluir(int id)
        {
            TransacaoModel objTransacao = new TransacaoModel(HttpContextAccessor);
            objTransacao.Excluir(id);
            return RedirectToAction("Index");
        }

        [HttpGet]        
        [HttpPost]
        public IActionResult Extrato(TransacaoModel formulario)
        {
            formulario.HttpContextAccessor = HttpContextAccessor;
            ViewBag.ListaTransacao = formulario.ListaTransacao();            
            ViewBag.ListaContas = new ContaModel(HttpContextAccessor).ListaConta();
            return View();
        }

        public IActionResult Dashboard()
        {
            List<Dashboard> lista = new Dashboard(HttpContextAccessor).RetornarDadosGraficoPie();
            string valores = "";
            string labels = "";
            string cores = "";
            var random = new Random();            

            for (int i = 0; i < lista.Count; i++)
            {
                valores += lista[i].Total.ToString() + ",";
                labels += "'" + lista[i].PlanoConta.ToString() + "',";
                cores += "'" + String.Format("#{0:X6}", random.Next(0x1000000)) + "',";
            }

            ViewBag.Cores = cores;
            ViewBag.Labels = labels;
            ViewBag.Valores = valores;

            return View();
        }
    }
}

MyFinance/Views/Transacao/Dashboard.cshtml
<h3>Meu Dashboard</h3>
<br /><br />
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>

<div id="canvas-holder" style="width:60%">
    <canvas id="chart-area"></canvas>
</div>

<script>
    var randomScalingFactor = function () {
        return Math.round(Math.random() * 100);
    };

    var config = {
        type: 'pie',
        data: {
            datasets: [{
                data: [@Html.Raw(ViewBag.Valores)],
                backgroundColor: [@Html.Raw(ViewBag.Cores)],
                label: 'Dataset 1'
            }],
            labels: [@Html.Raw(ViewBag.Labels)]
        },
        options: {
            responsive: true
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('chart-area').getContext('2d');
        window.myPie = new Chart(ctx, config);
    };

</script>

MyFinance/Views/Transacao/ExcluirTransacao.cshtml
<h3>Deseja Excluir a Transação Selecionada?</h3>

<p><strong>ID:</strong> @ViewBag.Registro.Id.ToString()</p>
<p><strong>Data:</strong> @ViewBag.Registro.Data.ToString()</p>
<p><strong>Histórico:</strong> @ViewBag.Registro.Descricao.ToString()</p>
<p><strong>Valor:</strong> @ViewBag.Registro.Valor.ToString()</p>

<button type="button" onclick="Cancelar()" class="btn btn-block btn-default">Cancelar</button>
<button type="button" onclick="Excluir(@ViewBag.Registro.Id.ToString())" class="btn btn-block btn-danger">Excluir</button>

<script>
    function Excluir(id)
    {
        window.location.href = "../../Transacao/Excluir/" + id;
    }

    function Cancelar()
    {
        window.location.href = "../../Transacao/Index";
    }
</script>

MyFinance/Views/Transacao/Extrato.cshtml
@model TransacaoModel

<h3>Meu Extrato</h3>

<div class="container">
    <form asp-controller="Transacao" asp-action="Extrato">
        <div class="form-group">
            <label>Data Transação (Início):</label>
            <input type="date" asp-for="Data" class="form-control">            
        </div>
        <div class="form-group">
            <label>Data Transação (Final):</label>
            <input type="date" asp-for="DataFinal" class="form-control">
        </div>
        <div class="form-group">
            <label>Tipo Transação:</label>
            <div class="radio"><label><input type="radio" asp-for="Tipo" value="A" checked>Receitas e Despesas</label></div>
            <div class="radio"><label><input type="radio" asp-for="Tipo" value="R">Receitas</label></div>
            <div class="radio"><label><input type="radio" asp-for="Tipo" value="D">Despesas</label></div>
        </div>
        <div class="form-group">
            <label>Conta:</label>
            <select asp-for="Conta_Id" class="form-control">
                @{
                    foreach (var item in (List<ContaModel>)ViewBag.ListaContas)
                    {                       
                       <option value="@item.Id.ToString()">@item.Nome.ToString()</option>
                       
                    }
                }
            </select>
        </div>
        <button type="submit" class="btn btn-block btn-success">Pesquisar</button> 
</form>
</div>
<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>ID</th>
            <th>Data</th>
            <th>Tipo</th>
            <th>Valor</th>
            <th>Histórico</th>
            <th>Conta</th>
            <th>Plano de Contas</th>
        </tr>
    </thead>

    @{
        var TotalReceitas = 0.0;
        var TotalDespesas = 0.0;
        var vSaldo = 0.0;

        foreach (var item in (List<TransacaoModel>)ViewBag.ListaTransacao)
        {
            <tbody>
                <tr>
                    <td><button type="button" class="btn btn-primary" onclick="Editar(@item.Id.ToString())">Editar</button></td>
                    <td>@item.Id.ToString()</td>
                    <td>@item.Data.ToString()</td>
                    <td>@item.Tipo.ToString().Replace("R", "Receita").Replace("D", "Despesa")</td>
                    <td>R$ @item.Valor.ToString()</td>
                    <td>@item.Descricao.ToString()</td>
                    <td>@item.NomeConta.ToString()</td>
                    <td>@item.DescricaoPlanoConta.ToString()</td>
                </tr>

                @{ 
                    if (item.Tipo =="D")
                    {
                        TotalDespesas += double.Parse(item.Valor.ToString());
                    }
                    else
                    {
                        TotalReceitas += double.Parse(item.Valor.ToString());
                    }
                }
            </tbody>
        }
        vSaldo = TotalReceitas - TotalDespesas;
    }

</table>

<h3><strong>Saldo: </strong>R$ @vSaldo</h3>

<script>
    function Editar(id) {
        window.location.href = "../Transacao/Registrar/" + id;
    }
</script>

MyFinance/Views/Transacao/Index.cshtml
<h3>Minhas Transações</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>#</th>
            <th>ID</th>
            <th>Data</th>
            <th>Tipo</th>
            <th>Valor</th>
            <th>Histórico</th>
            <th>Conta</th>
            <th>Plano de Contas</th>            
        </tr>
    </thead>

    @{
        foreach (var item in (List<TransacaoModel>)ViewBag.ListaTransacao)
        {
            <tbody>
                <tr>
                    <td><button type="button" class="btn btn-primary" onclick="Editar(@item.Id.ToString())">Editar</button></td>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
                    <td>@item.Id.ToString()</td>
                    <td>@item.Data.ToString()</td>
                    <td>@item.Tipo.ToString().Replace("R", "Receita").Replace("D", "Despesa")</td>                    
                    <td>R$ @item.Valor.ToString()</td>
                    <td>@item.Descricao.ToString()</td>
                    <td>@item.NomeConta.ToString()</td>
                    <td>@item.DescricaoPlanoConta.ToString()</td>
                    
                </tr>
            </tbody>
        }
    }

</table>

<button type="button" class="btn btn-block btn-primary" onclick="RegistrarTransacao()">Registrar Transação</button>

<script>
    function RegistrarTransacao()
    {
        window.location.href = "../Transacao/Registrar";
    }

    function Excluir(id)
    {
        window.location.href = "../Transacao/ExcluirTransacao/" + id;
    }

    function Editar(id) {
        window.location.href = "../Transacao/Registrar/" + id;
    }
</script>

MyFinance/Views/Transacao/Registrar.cshtml
@model TransacaoModel

<h3>Registrar uma Transação</h3>

@{
    var vData = "";
    var vDescricao = "";
    var vTipo = "";
    var vValor = 0.0;
    var vId = 0;
    var vContaId = 0;
    var vPlanoContaId = 0;

    try
    {
        vId = int.Parse(@ViewBag.Registro.Id.ToString());
        vData = DateTime.Parse(@ViewBag.Registro.Data.ToString()).ToString("yyyy-MM-dd");
        vContaId = int.Parse(@ViewBag.Registro.Conta_Id.ToString());
        vPlanoContaId = int.Parse(@ViewBag.Registro.Plano_Contas_Id.ToString());
        vDescricao = @ViewBag.Registro.Descricao.ToString();
        vTipo = @ViewBag.Registro.Tipo.ToString();
        vValor = double.Parse(@ViewBag.Registro.Valor.ToString());
    }
    catch { }
}
<form asp-controller="Transacao" asp-action="Registrar">
    <input type="hidden" asp-for="Id" value="@vId" />

    <div class="form-group">
        <label>Data:</label>
        <input type="date" class="form-control" asp-for="Data" value="@vData">
        <span asp-validation-for="Data" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Tipo:</label>

        @{
            if (vTipo == "R")
            {
                <div class="radio"><label><input type="radio" asp-for="Tipo" value="R" checked>Receita</label></div>
                    <div class="radio"><label><input type="radio" asp-for="Tipo" value="D" unchecked>Despesa</label></div>
            }
            else
            {
                <div class="radio"><label><input type="radio" asp-for="Tipo" value="R" unchecked>Receita</label></div>
                    <div class="radio"><label><input type="radio" asp-for="Tipo" value="D" checked>Despesa</label></div>
            }
        }
    </div>

    <div class="form-group">
        <label>Valor:</label>
        <input type="number" class="form-control" asp-for="Valor" value="@vValor">
        <span asp-validation-for="Valor" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Histórico:</label>
        @Html.TextArea("Descricao", vDescricao, new { @class = "form-control" })
        <span asp-validation-for="Descricao" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Conta:</label>
        <select asp-for="Conta_Id" class="form-control">
            @{
                foreach (var item in (List<ContaModel>)ViewBag.ListaContas)
                {
                    if (item.Id.ToString() == vContaId.ToString())
                    {
                        <option selected value="@item.Id.ToString()">@item.Nome.ToString()</option>
                    }
                    else
                    {
                        <option value="@item.Id.ToString()">@item.Nome.ToString()</option>
                    }
                }
            }
        </select>
    </div>

    <div class="form-group">
        <label>Plano de Contas:</label>
        <select asp-for="Plano_Contas_Id" class="form-control">
            @{
                foreach (var item in (List<PlanoContaModel>)ViewBag.ListaPlanoContas)
                {
                    if (item.Id.ToString() == vPlanoContaId.ToString())
                    {
                        <option selected value="@item.Id.ToString()">@item.Descricao.ToString()</option>
                    }
                    else
                    {
                        <option value="@item.Id.ToString()">@item.Descricao.ToString()</option>

                    }
                }
            }
        </select>
    </div>

    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>